Poisson Regression

Purpose: Count data, assuming the variable Y has a Poisson Distribution

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import minimize
from scipy.special import factorial

In [4]:
#data train
file_train='D:\\Project\\Data_Mining\\Finals_BlogCommentPrediction\\Data_Ucimlrepo\\Train\\blogData_train.csv'
train=pd.read_csv(file_train, header=None)

#data test
file_test='D:\\Project\\Data_Mining\\Finals_BlogCommentPrediction\\Data_Ucimlrepo\\Test\\blogData_test.csv'
test=pd.read_csv(file_test, header=None)

train = train.drop(train.columns[:50], axis=1)  # Drop the first 50 columns
test = test.drop(test.columns[:50], axis=1)  # Drop the first 50 columns

print(train.isnull().values.any())
print(test.isnull().values.any())
test.fillna(value=0, inplace=True)
print(test.isnull().values.any())
# Split features and labels
X_train = train.iloc[:, :-1]
y_train = train.iloc[:, -1]
X_test = test.iloc[:, :-1]
y_test = test.iloc[:, -1]
X_test

False
True
False

C:\Users\scarl\AppData\Local\Temp\ipykernel_9492\1419871668.py:7: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  test=pd.read_csv(file_test, header=None)

,50,51,52,53,54,55,56,57,58,59,...,270,271,272,273,274,275,276,277,278,279
0,35.0,35.0,0.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21.0,0.0,2.0,21.0,-2.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,2.0,2.0,0.0,2.0,2.0,2.0,2.0,0.0,2.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.0,3.0,0.0,3.0,3.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7620,2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7621,3.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7622,8.0,8.0,0.0,8.0,8.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7623,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7624,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
# Print the sum of NaN values to confirm their presence
print("NaN values in y_test before:", y_test.isna().sum())

# Replace NaN with 1
y_test.fillna(1, inplace=True)

# Verify the replacement
print("NaN values in y_test after:", y_test.isna().sum())

print(y_test)

NaN values in y_test before: 0
NaN values in y_test after: 0
0       4.0
1       0.0
2       1.0
3       5.0
4       0.0
       ...
7620    0.0
7621    0.0
7622    3.0
7623    0.0
7624    0.0
Name: 280, Length: 7625, dtype: float64

In [6]:
from sklearn.linear_model import PoissonRegressor
model = PoissonRegressor(fit_intercept=True, alpha=0.3, max_iter=10)

In [7]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

C:\Users\scarl\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_linear_loss.py:294: RuntimeWarning: invalid value encountered in matmul
  grad[:n_features] = X.T @ grad_pointwise + l2_reg_strength * weights

array([6.76471935, 6.76471935, 6.76471935, ..., 6.76471935, 6.76471935,
       6.76471935])

In [11]:
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error
# Calculate MSE
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)  # Root Mean Squared Error

print("Poisson Regression model results")
print("Mean Squared Error:", mse)
print(f'RMSE : {rmse}')

mae = mean_absolute_error(y_test, y_pred)

print(f'Mean Absolute Error (MAE): {mae}')

Poisson Regression model results
Mean Squared Error: 932.1475597883109
RMSE : 30.53109169008391
Mean Absolute Error (MAE): 9.882595305637883

Mean Absolute Error (MAE): 9.882595305637883

In [ ]:
import joblib

joblib.dump(model, 'poisson_regression.joblib')

['poisson_regression.joblib']